sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build --verbose
addons:
  apt:
    sources:
        - kalakris-cmake
    packages:
        - cmake
env:
  global:
    secure: JLBlgHY6OEmhJ8woewNJHmuBokTNUv7/WvLkJGV8xk0t6bXBwSU0jNloXwlH7FiQTc4TccX0PumPDD4MrMgxIAVFPmmmlQOCmdpYP4tqZJ8xo189E5zk8lKF5OyaVYCs5SMmFC3cxCsKjfwGIexNu3ck5Uhwe9jI0tqgkgM3URA=
